# From SQL to pandas challenge 11

In [ ]:
# import libraries
import pandas as pd

# load data
# This code is made to load our data stored on Google Drive
def gd_path(file_id):
    """Generate a shareable link from Google Drive file id."""
    return f"https://drive.google.com/uc?export=download&id={file_id}"

# Google Drive file ids
files_id = {
    "titleauthor": "1F1JOiYXStWacOBca6coNVfyVtoST7ZgD",
    "titles": "1PLdn50N9GRa53ZbuVWo0l47F_IXdvlEm",
    "stores": "1f-GCgip7O93CpbAkYvOsc21eKnSOSHsQ", 
    "sales": "1fzFc9rwYmVIPaGOFmhLVxCi3kg19vNU2", 
    "roysched": "1zPRZPoFPEMKyrNR5VSENeYFHGCBZmxbs", 
    "publishers": "1s9E8_AVOziTrowb3wyh2jg3PV763VOyq",
    "pub_info": "1OEgogcGKy--EpuVj0kqq7lyBZNGW6YSv", 
    "jobs": "1V1Za8hUdXD-vJOyRdX4aQV5wanIff2eM", 
    "employee": "1h9mUjsVqpP74b1w0x7KOw37n_n9Ulkt5", 
    "discounts": "111dvSxMcCsTgOuV1wDSKFJxO1Xcxd9VS", 
    "authors": "1fEF89Nhe61EebAljKlwFwfEuokK0o6aJ"
}

# Read data from Google Drive
sales = pd.read_csv(gd_path(files_id["sales"]), sep=";")
titles = pd.read_csv(gd_path(files_id["titles"]), sep=";")
publishers = pd.read_csv(gd_path(files_id["publishers"]), sep=";")
employee = pd.read_csv(gd_path(files_id["employee"]), sep=";")
authors = pd.read_csv(gd_path(files_id["authors"]), sep=";")
titleauthor = pd.read_csv(gd_path(files_id["titleauthor"]), sep=";")
roysched = pd.read_csv(gd_path(files_id["roysched"]), sep=";")

## 1. Using LEFT JOIN: in which cities has "Is Anger the Enemy?" been sold?

In [ ]:
p = publishers
t = titles

df = t.merge(p, on="pub_id", how="left")

df[["title", "city"]] [df["title"] == "Is Anger the Enemy?"]

                  title    city
11  Is Anger the Enemy?  Boston

### Hint:

In SQL the syntax is:

```sql
SELECT p.city
FROM publishers AS p
LEFT JOIN titles AS t
ON p.pub_id = t.pub_id
WHERE t.title = 'Is Anger the Enemy?';
```

## 2. Select all the book titles that have a link to the employee Howard Snyder 
    (he works for the publisher that has published those books).

In [ ]:
e = employee

df = t.merge(e, on="pub_id", how="inner")

df[["title", "fname", "lname"]] [ (df["fname"] =="Howard") & (df["lname"] == "Snyder")]

                                             title   fname   lname
61                 You Can Combat Computer Stress!  Howard  Snyder
71                             Is Anger the Enemy?  Howard  Snyder
81                               Life Without Fear  Howard  Snyder
91   Prolonged Data Deprivation: Four Case Studies  Howard  Snyder
101            Emotional Security: A New Algorithm  Howard  Snyder

### Hint:

In SQL the syntax is:

```sql
SELECT t.title
FROM employee e
JOIN titles t
ON e.pub_id = t.pub_id
WHERE e.fname = 'Howard'
AND e.lname = 'Snyder';
```

## 3. Using the `merge` of your choice: Select the book title with highest number of sales (qty)

In [ ]:
s = sales

df = t.merge(s, on="title_id", how="inner")

(
    df.groupby("title")
    .qty.sum()
    .sort_values(ascending=False)
    .head(1)
)

title
Is Anger the Enemy?    108
Name: qty, dtype: int64

### Hint:

In SQL the syntax is:

```sql
SELECT t.title, SUM(qty)
FROM sales AS s 
JOIN titles t
ON s.title_id = t.title_id
GROUP BY t.title_id
ORDER BY SUM(qty) desc
LIMIT 1;
```

# 4. Select all book titles and the full name of their author(s).
      
      - If a book has multiple authors, all authors must be displayed (in 
      multiple rows).
      
      - Books with no authors and authors with no books should not be displayed.

In [ ]:
a = authors
ta = titleauthor

df = ta.merge(t, on="title_id", how="inner").merge(a, on="au_id", how="inner")

df[["title", "au_fname", "au_lname"]]

,title,au_fname,au_lname
0,Prolonged Data Deprivation: Four Case Studies,Johnson,White
1,The Busy Executive's Database Guide,Marjorie,Green
2,You Can Combat Computer Stress!,Marjorie,Green
3,The Busy Executive's Database Guide,Abraham,Bennet
4,But Is It User Friendly?,Cheryl,Carson
5,Cooking with Computers: Surreptitious Balance ...,Michael,O'Leary
6,"Sushi, Anyone?",Michael,O'Leary
7,Cooking with Computers: Surreptitious Balance ...,Stearns,MacFeather
8,Computer Phobic AND Non-Phobic Individuals: Be...,Stearns,MacFeather
9,"Sushi, Anyone?",Burt,Gringlesby
10,"Sushi, Anyone?",Akiko,Yokomoto
11,Straight Talk About Computers,Dean,Straight
12,Secrets of Silicon Valley,Ann,Dull
13,Secrets of Silicon Valley,Sheryl,Hunter
14,Net Etiquette,Charlene,Locksley
15,Emotional Security: A New Algorithm,Charlene,Locksley
16,Fifty Years in Buckingham Palace Kitchens,Reginald,Blotchet-Halls
17,Silicon Valley Gastronomic Treats,Innes,del Castillo
18,The Gourmet Microwave,Michel,DeFrance
19,The Gourmet Microwave,Anne,Ringer
20,Is Anger the Enemy?,Anne,Ringer
21,Computer Phobic AND Non-Phobic Individuals: Be...,Livia,Karsen
22,"Onions, Leeks, and Garlic: Cooking Secrets of ...",Sylvia,Panteley
23,Is Anger the Enemy?,Albert,Ringer
24,Life Without Fear,Albert,Ringer

### Hint:

In SQL the syntax is:

```sql
SELECT
    t.title,
    a.au_fname,
    a.au_lname
FROM titles t
INNER JOIN titleauthor ta 
ON t.title_id = ta.title_id
INNER JOIN authors a 
ON ta.au_id = a.au_id;
```

## 5. Select the full name of authors of Psychology books

   Bonus hint: if you want to prevent duplicates but allow authors with shared
   last names to be displayed, you can concatenate the first and last names
   with CONCAT(), and use the DISTINCT clause on the concatenated names.

In [ ]:
df = t.merge(ta, on="title_id", how="inner").merge(a, on="au_id", how="inner")

df[["type", "au_fname", "au_lname"]] [df["type"] == "psychology"]

          type  au_fname    au_lname
6   psychology   Stearns  MacFeather
11  psychology      Anne      Ringer
16  psychology  Charlene    Locksley
17  psychology     Livia      Karsen
18  psychology    Albert      Ringer
19  psychology    Albert      Ringer
20  psychology   Johnson       White

### Hint:

In SQL the syntax is:

```sql
SELECT DISTINCT CONCAT(a.au_fname, " ", a.au_lname) AS full_name
FROM authors a
INNER JOIN titleauthor ta ON a.au_id = ta.au_id
INNER JOIN titles t ON ta.title_id = t.title_id
WHERE t.type = "Psychology";
```

## 6. Explore the table roysched and try to grasp the meaning of each column. 
   The notes below will help:
   
   - "Royalty" means the percentage of the sale price paid to the author(s).
   
   - Sometimes, the royalty may be smaller for the first few sales (which have
     to cover the publishing costs to the publisher) but higher for the sales 
     above a certain threshold.
     
   - In the "roysched" table each title_id can appear multiple times, with
     different royalty values for each range of sales.
     
   - Select all rows for particular title_id, for example "BU1111", and explore
	 the data.

In [ ]:
roysched[roysched["title_id"] == "BU1111"]

   title_id  lorange  hirange  royalty
49   BU1111        0     4000       10
50   BU1111     4001     8000       12
51   BU1111     8001    10000       14
52   BU1111    12001    16000       16
53   BU1111    16001    20000       18
54   BU1111    20001    24000       20
55   BU1111    24001    28000       22
56   BU1111    28001    50000       24

### Hint:

In SQL the syntax is:

```sql
SELECT * FROM roysched WHERE title_id = "BU1111";
```

## 7. Select all the book titles and the maximum royalty they can reach.
    Display only titles that are present in the roysched table.

In [ ]:
r = roysched

df = pd.merge(t, r, on="title_id", how="inner")

df.groupby("title").royalty_y.max().sort_values(ascending=False)

title
Cooking with Computers: Surreptitious Balance Sheets               24
Onions, Leeks, and Garlic: Cooking Secrets of the Mediterranean    24
Straight Talk About Computers                                      24
The Gourmet Microwave                                              24
You Can Combat Computer Stress!                                    24
Fifty Years in Buckingham Palace Kitchens                          22
Silicon Valley Gastronomic Treats                                  20
But Is It User Friendly?                                           18
Computer Phobic AND Non-Phobic Individuals: Behavior Variations    18
Is Anger the Enemy?                                                16
Life Without Fear                                                  16
Prolonged Data Deprivation: Four Case Studies                      16
Secrets of Silicon Valley                                          16
Sushi, Anyone?                                                     14
Emotional Security: A New Algorithm                                12
The Busy Executive's Database Guide                                12
Name: royalty_y, dtype: int64

### Hint:

In SQL the syntax is:

```sql
SELECT t.title, MAX(r.royalty) max_royalty
FROM titles t
INNER JOIN roysched r 
ON t.title_id = r.title_id
GROUP BY t.title
ORDER BY max_royalty DESC;
```